version: '3'
services:
    rabbitmqserver:
        image: rabbitmq
        restart: always
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 30s
            timeout: 30s
            retries: 3
    auth_service:
        build: ./auth-service-module/
        restart: always
        environment:
            AMQP_SERVER: rabbitmqserver
            EXCHANGE_NAME: DEFAULT_EXCHANGE
            JWT_SECRET: SECRET_JWT
        depends_on:
            rabbitmqserver:
                condition: service_healthy
    message_service:
        build: ./message-service-module
        restart: always
        environment:
            AMQP_SERVER: rabbitmqserver
            EXCHANGE_NAME: DEFAULT_EXCHANGE
            JWT_SECRET: SECRET_JWT
        depends_on:
            rabbitmqserver:
                condition: service_healthy
    tts_service:
        build: ./tts-service-module/
        restart: always
        environment:
            RABBITMQ: rabbitmqserver
            EXCHANGE_NAME: DEFAULT_EXCHANGE
        depends_on:
            rabbitmqserver:
                condition: service_healthy
    log_service:
        build: ./log-module/
        restart: always
        environment:
            AMQP_SERVER: rabbitmqserver
            EXCHANGE_NAME: DEFAULT_EXCHANGE
        depends_on:
            rabbitmqserver:
                condition: service_healthy
    web_app:
        build: 
            context: ./front-end
            args:
                VITE_AUTH_SERVICE: http://auth_service:3000
                VITE_TTS_SERVICE: http://tts_service:3000
                VITE_MESSAGE_SERVICE: http://message_service:3000
        restart: always
        ports:
            - 3000:80

    

